### ISSUE TITLE
Login with token

### ISSUE THREAD

**Issue by dae-vinity** [mcxiv/10cord#4]
Add a way to login with your token, using --token/-t <token> for example.

**Comment by mcxiv** [comment]
@daemon-git What is your use case?

**Comment by dae-vinity** [comment]
> @daemon-git What is your use case?

makes login easier for me personally.

**Comment by mcxiv** [comment]
@daemon-git Please, take a look at **[this branch](https://github.com/mcxiv/10cord/tree/feature/token_argument)** and tell me what you think. :)
(You can pass two empty strings for the email and password)

**Comment by dae-vinity** [comment]
@mcxiv i apologize for my delay, but works like a charm. thanks! :)
